import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({
  container: {
    alignItems: "center",
    backgroundColor: "#fff",
    height: "100%",
  },
  board: {
    height: "auto",
    width: "100%",
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  top: {
    height: 80,
    width: "100%",
    paddingTop: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "pink",
  },
  setting: {
    position: "absolute",
    right: 15,
    top: 28,
  },
  note: {
    fontSize: 30,
    fontWeight: "bold",
  },
  noSeal: {
    height: 70,
    width: 70,
    margin: "0.5%",
    borderStyle: "dotted",
    borderRadius: 50,
    borderWidth: 3,
    borderColor: "pink",
  },
  seal: {
    height: 70,
    width: 70,
    margin: "0.5%",
    borderRadius: 50,
    backgroundColor: "#ff006f",
    alignItems: "center",
    justifyContent: "center",
  },
  sealButton: {
    position: "relative",
    bottom: 20,
    backgroundColor: "#ff2599",
    borderRadius: 20,
    paddingHorizontal: 50,
    paddingVertical: 25,
  },
  buttonText: {
    fontSize: 25,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
  },
  sealText: {
    fontSize: 40,
    fontWeight: "bold",
    color: "white",
  },
  modalCenter: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    opacity: 0.99,
  },
  editSeal: {
    alignItems: "center",
    width: "80%",
    paddingVertical: 20,
    backgroundColor: "#dcdcdc",
    borderRadius: 20,
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  confirmButton: {
    backgroundColor: "red",
    borderRadius: 20,
    width: 130,
    paddingVertical: 20,
    marginTop: 15,
  },
  picker: {
    height: 200,
    width: "80%",
  },
  pickerItem: {
    fontWeight: "bold",
    fontSize: 30,
  },
  close: {
    position: "absolute",
    right: 10,
    top: 10,
  },
  yesnoButton: {
    flexDirection: "row",
    marginTop: 25,
  },
  noButton: {
    width: 130,
    backgroundColor: "gray",
    borderRadius: 20,
    paddingVertical: 20,
    marginHorizontal: 10,
  },
  yesButton: {
    width: 130,
    backgroundColor: "red",
    borderRadius: 20,
    paddingVertical: 20,
    marginHorizontal: 10,
  },
  configBoard: {
    width: "100%",
    alignItems: "center",
  },
  setModule: {
    flexDirection: "row",
    marginVertical: "5%",
  },
  setGoal: {
    flex: 1,
    alignItems: "center",
  },
  stdText: {
    fontSize: 20,
    fontWeight: "bold",
  },
  multiplication: {
    fontSize: 30,
    marginTop: 120,
  },
  bbuttonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "red",
    textAlign: "center",
  },
  initButton: {
    marginTop: 10,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "red",
    width: 220,
    paddingVertical: 20,
  },
});
